// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS_v2.DataAccess.Entities
{

    // Audit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Audit
    {
        public int Id { get; set; } // Id (Primary key)
        public System.DateTime BookingDate { get; set; } // BookingDate
        public int FlightId { get; set; } // FlightId
        public int SeatId { get; set; } // SeatId

        public Audit()
        {
            BookingDate = System.DateTime.Now;
        }
    }

}
// </auto-generated>
