// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS_v2.DataAccess.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class FindAvailableFlightsReturnModel
    {
        public System.String FlightName { get; set; }
        public System.String AirlineName { get; set; }
        public System.String OriginAirport { get; set; }
        public System.String DestinationAIrport { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.Decimal Price { get; set; }
    }

}
// </auto-generated>
