// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS_v2.DataAccess.Entities
{

    // FlightSection
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class FlightSection
    {
        public int Id { get; set; } // Id (Primary key)
        public int SectionClassId { get; set; } // SectionClassId
        public int FlightId { get; set; } // FlightId

        // Reverse navigation

        /// <summary>
        /// Child Seats where [Seat].[FlightSectionId] point to this entity (FK_FlightSection_Seat)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Seat> Seats { get; set; } // Seat.FK_FlightSection_Seat

        // Foreign keys

        /// <summary>
        /// Parent Flight pointed by [FlightSection].([FlightId]) (FK_Flight_FlightSection)
        /// </summary>
        public virtual Flight Flight { get; set; } // FK_Flight_FlightSection
        /// <summary>
        /// Parent SectionClass pointed by [FlightSection].([SectionClassId]) (FK_SectionClass_FlightSection)
        /// </summary>
        public virtual SectionClass SectionClass { get; set; } // FK_SectionClass_FlightSection

        public FlightSection()
        {
            Seats = new System.Collections.Generic.List<Seat>();
        }
    }

}
// </auto-generated>
