// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS_v2.DataAccess.Entities
{

    // SectionClass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class SectionClass
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child FlightSections where [FlightSection].[SectionClassId] point to this entity (FK_SectionClass_FlightSection)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FlightSection> FlightSections { get; set; } // FlightSection.FK_SectionClass_FlightSection

        public SectionClass()
        {
            FlightSections = new System.Collections.Generic.List<FlightSection>();
        }
    }

}
// </auto-generated>
