// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS_v2.DataAccess.Entities
{

    // vSystemDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class VSystemDetail
    {
        public string FlightName { get; set; } // FlightName (Primary key) (length: 50)
        public string AirlineName { get; set; } // AirlineName (Primary key) (length: 6)
        public string OriginAirportName { get; set; } // OriginAirportName (Primary key) (length: 3)
        public string DestinationAirportName { get; set; } // DestinationAirportName (Primary key) (length: 3)
        public string SeatClass { get; set; } // SeatClass (Primary key) (length: 50)
        public int Row { get; set; } // Row (Primary key)
        public string Col { get; set; } // Col (Primary key) (length: 1)
        public bool Status { get; set; } // Status (Primary key)
    }

}
// </auto-generated>
