// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS_v2.DataAccess.Configuration
{
    using ABS_v2.DataAccess.Entities;

    // Audit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AuditConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Audit>
    {
        public AuditConfiguration()
            : this("dbo")
        {
        }

        public AuditConfiguration(string schema)
        {
            ToTable("Audit", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BookingDate).HasColumnName(@"BookingDate").HasColumnType("datetime").IsRequired();
            Property(x => x.FlightId).HasColumnName(@"FlightId").HasColumnType("int").IsRequired();
            Property(x => x.SeatId).HasColumnName(@"SeatId").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
